### ISSUE TITLE
Status of Adding Z20.588 and other new COVID ICD10 Codes

### ISSUE THREAD

**Issue by kmkostka** [OHDSI/Vocabulary-v4.5#5]
ICD10 released [new COVID ICD10 codes in January 2021](https://www.aappublications.org/news/2021/01/13/coding011321). We're now 2 months after this release and these codes are not incorporated in a vocabulary release.

When can vocabulary users expect to see an ICD10 vocabulary update? Is there a release schedule of upcoming vocabularies being integrated?

**Comment by mik-ohdsi** [comment]
Hi Kristin, thanks for your trust in the vocabulary team's ability to swiftly refresh all vocabs :-)
We simply didn't notice this "out of the regular schedule" addition.
Karthik has already highlighted that issue to us [here](https://github.com/OHDSI/Vocabulary-v5.0/issues/469). We are currently in the process of finalizing it and will release early next week. If this is an emergency request for you and a deadline would be threatened, let us know and maybe we can find a way to speed it up. If not, you'll have it next week. 
Your general question about a release schedule is touching a different topic. There are deliberations to form something like a "Vocabulary Board" to deal with prioritizing vocabulary work as it is now only Christian handling this and the CDM workgroup has their hands full with other stuff. Watch out for some announcement in the near future.
Cheers ~ Mik
